services:
  backend:
    container_name: backend
    build: ./
    ports:
      - "5000:5000"
    networks:
      - sad-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      PROFILE_BUCKET: ${PROFILE_BUCKET}
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: ${NODE_ENV}


networks:
  sad-app:
    driver: bridge
      
      