services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - /var/lib/mysql
    ports:
        - 3306:3306
    environment:
      MYSQL_DATABASE: pcbeedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234 
      SERVICE_TAGS: dev
      SERVICE_name: mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
      
      